# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 07:27
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160903_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='call_for_speakers_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
