# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160907_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='sponsors_partnership_document_link',
        ),
    ]
