# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_homepage_sponsors_partnership_document_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='video_url',
            new_name='website_url',
        ),
    ]
