# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_partner_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='webpage',
            new_name='video_url',
        ),
    ]
