# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20160907_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingPartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_organized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.Partner'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_powered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.Partner'),
        ),
        migrations.AddField(
            model_name='hostingpartners',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_partners', to='website.HomePage'),
        ),
        migrations.AddField(
            model_name='hostingpartners',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='website.Partner'),
        ),
    ]
