# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('website', '0013_auto_20160907_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sponsors_partnership_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
