# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_otherpartners'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sweet_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.Partner'),
        ),
    ]
