# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-03 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('webpage', models.URLField(blank=True, max_length=255, null=True)),
                ('description', wagtail.wagtailcore.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralPartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaPartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url', models.URLField(blank=True, max_length=255, null=True)),
                ('description', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PastEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='website.Event')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='howweworkpage',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='howweworkpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='howweworkpage',
            name='what_we_do_image',
        ),
        migrations.RemoveField(
            model_name='ourteampage',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='ourteampage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='projectsplacement',
            name='page',
        ),
        migrations.RemoveField(
            model_name='projectsplacement',
            name='project',
        ),
        migrations.RemoveField(
            model_name='teammate',
            name='initial_photo',
        ),
        migrations.RemoveField(
            model_name='teammate',
            name='secondary_photo',
        ),
        migrations.RemoveField(
            model_name='teammatepageplacement',
            name='page',
        ),
        migrations.RemoveField(
            model_name='teammatepageplacement',
            name='teammate',
        ),
        migrations.RemoveField(
            model_name='teammateplacement',
            name='page',
        ),
        migrations.RemoveField(
            model_name='teammateplacement',
            name='teammate',
        ),
        migrations.RemoveField(
            model_name='technologiespageplacement',
            name='page',
        ),
        migrations.RemoveField(
            model_name='technologiespageplacement',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='technologiesplacement',
            name='page',
        ),
        migrations.RemoveField(
            model_name='technologiesplacement',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='technologiesweusepage',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='technologiesweusepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='how_we_work_center',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='how_we_work_left',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='how_we_work_right',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='how_we_work_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_h1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_h2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='our_team_center',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='our_team_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='portfolio_center',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='portfolio_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='portfolio_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='technologies_we_use_center',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='technologies_we_use_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='technologies_we_use_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='call_for_speakers_form_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_image_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='location_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='speakers_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tickets_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tickets_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tickets_widget_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='HowWeWorkPage',
        ),
        migrations.DeleteModel(
            name='OurTeamPage',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectsPlacement',
        ),
        migrations.DeleteModel(
            name='Teammate',
        ),
        migrations.DeleteModel(
            name='TeammatePagePlacement',
        ),
        migrations.DeleteModel(
            name='TeammatePlacement',
        ),
        migrations.DeleteModel(
            name='TechnologiesPagePlacement',
        ),
        migrations.DeleteModel(
            name='TechnologiesPlacement',
        ),
        migrations.DeleteModel(
            name='TechnologiesWeUsePage',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.AddField(
            model_name='pastevents',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_events', to='website.HomePage'),
        ),
        migrations.AddField(
            model_name='mediapartners',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_partners', to='website.HomePage'),
        ),
        migrations.AddField(
            model_name='mediapartners',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='website.Partner'),
        ),
        migrations.AddField(
            model_name='generalpartners',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_partners', to='website.HomePage'),
        ),
        migrations.AddField(
            model_name='generalpartners',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='website.Partner'),
        ),
        migrations.AddField(
            model_name='branchpartners',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_partners', to='website.HomePage'),
        ),
        migrations.AddField(
            model_name='branchpartners',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='website.Partner'),
        ),
    ]
