# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('website', '0006_auto_20160907_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
