# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20160907_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_dates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
