# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-11 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_homepage_sweet_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='transport_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.Partner'),
        ),
    ]
