# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-14 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_homepage_transport_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='live_stream',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
