# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-29 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20170329_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sweet_partner_title_bg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sweet_partner_title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='transport_partner_title_bg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='transport_partner_title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
