# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-29 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20170329_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_bg',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name_bg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
