# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-29 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_navigationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='navigationitem',
            name='page',
        ),
        migrations.AddField(
            model_name='navigationitems',
            name='navigation_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='website.NavigationItem'),
        ),
        migrations.AddField(
            model_name='navigationitems',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='website.HomePage'),
        ),
    ]
