# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-29 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20170329_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='name_bg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='name_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
