# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-30 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20170329_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='name_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
