# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-30 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_auto_20170330_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='lector',
        ),
        migrations.AddField(
            model_name='lecture',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='website.Speaker'),
        ),
    ]
