# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-30 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20170330_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='topic_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='topic_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
