# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-03 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_auto_20170330_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='sweet_partner',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='sweet_partner_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='sweet_partner_title_bg',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='sweet_partner_title_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='transport_partner',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='transport_partner_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='transport_partner_title_bg',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='transport_partner_title_en',
        ),
    ]
