# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-05 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('website', '0038_auto_20170403_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer_code_of_conduct_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_press_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
