# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-07 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_auto_20170405_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_sponsors_section',
            field=models.BooleanField(default=False),
        ),
    ]
