# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-24 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_homepage_show_sponsors_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_branch_partners',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_general_partners',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_gold_partners',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_media_partners',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_other_partners',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_platinum_partners',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_silver_partners',
            field=models.BooleanField(default=True),
        ),
    ]
