# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-12 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_auto_20170524_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workshop_enroll_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
