# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-12 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_workshop_workshop_enroll_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='workshop_enroll_url',
            new_name='enroll_url',
        ),
    ]
