# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-10-09 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_auto_20170912_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_tickets',
            field=models.BooleanField(default=True),
        ),
    ]
