# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('website', '0044_homepage_show_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='call_for_speakers_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
