# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('website', '0045_homepage_call_for_speakers_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='footer_press_document',
            new_name='footer_privacy_policy_document',
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_terms_and_conditions_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
