# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_auto_20180314_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='pre_register_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pre_register_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_pre_register',
            field=models.BooleanField(default=False),
        ),
    ]
