# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 13:19
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_auto_20180314_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='pre_register_text_bg',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pre_register_text_en',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
